from __future__ import annotations

from dataclasses import dataclass


@dataclass
class ToolCall:
    id: str        # Anthropic requires matching this ID in the result
    name: str
    arguments: dict


@dataclass
class ToolResult:
    id: str        # matches ToolCall.id
    content: str
    is_error: bool = False


@dataclass
class BoundTool:
    """A tool schema and its implementation in one object.

    Subclass and override process(). Constructor accepts name, description, schema
    as positional/keyword args (generated by @dataclass).
    """

    name: str
    description: str
    schema: dict   # JSON Schema for the parameters accepted by this tool

    async def process(self, arguments: dict) -> str:
        raise NotImplementedError
